apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp-rc
    app: myapp
    types: rc
spec:
 template:
    metadata:
      name: myapp-Pod
      labels:
        name: myapp-Pod
        app: myapp
        types: Pod
    spec:
      containers:
    - name: nginx-container
      image: nginx
 replicas: 5
